/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  AccessTokens: () => import('#controllers/access_tokens_controller'),
  admin: {
    Analytics: () => import('#controllers/admin/analytics_controller'),
    AppelsOffres: () => import('#controllers/admin/appels_offres_controller'),
    Demandes: () => import('#controllers/admin/demandes_controller'),
    Offres: () => import('#controllers/admin/offres_controller'),
    Users: () => import('#controllers/admin/users_controller'),
  },
  AppelsOffres: () => import('#controllers/appels_offres_controller'),
  Demandes: () => import('#controllers/demandes_controller'),
  Documents: () => import('#controllers/documents_controller'),
  Messages: () => import('#controllers/messages_controller'),
  NewAccount: () => import('#controllers/new_account_controller'),
  Notifications: () => import('#controllers/notifications_controller'),
  Offres: () => import('#controllers/offres_controller'),
  Profile: () => import('#controllers/profile_controller'),
}
