/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class AppelOffreEntrepriseSchema extends BaseModel {
  static $columns = ['appelOffreId', 'createdAt', 'entrepriseId', 'id', 'notifieAt', 'updatedAt'] as const
  $columns = AppelOffreEntrepriseSchema.$columns
  @column()
  declare appelOffreId: number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare entrepriseId: number
  @column({ isPrimary: true })
  declare id: number
  @column.dateTime()
  declare notifieAt: DateTime | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class AppelsOffreSchema extends BaseModel {
  static $columns = ['createdAt', 'delaiReponse', 'demandeId', 'id', 'lancePar', 'statut', 'updatedAt'] as const
  $columns = AppelsOffreSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime()
  declare delaiReponse: DateTime
  @column()
  declare demandeId: number
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare lancePar: number
  @column()
  declare statut: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class AuthAccessTokenSchema extends BaseModel {
  static $columns = ['abilities', 'createdAt', 'expiresAt', 'hash', 'id', 'lastUsedAt', 'name', 'tokenableId', 'type', 'updatedAt'] as const
  $columns = AuthAccessTokenSchema.$columns
  @column()
  declare abilities: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.dateTime()
  declare expiresAt: DateTime | null
  @column()
  declare hash: string
  @column({ isPrimary: true })
  declare id: number
  @column.dateTime()
  declare lastUsedAt: DateTime | null
  @column()
  declare name: string | null
  @column()
  declare tokenableId: number
  @column()
  declare type: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class DemandeSchema extends BaseModel {
  static $columns = ['budgetMax', 'clientId', 'createdAt', 'delaiSouhaite', 'description', 'id', 'localisationAdresse', 'localisationLat', 'localisationLng', 'profondeurEstimee', 'statut', 'typeForage', 'updatedAt', 'validatedAt', 'validatedBy'] as const
  $columns = DemandeSchema.$columns
  @column()
  declare budgetMax: string
  @column()
  declare clientId: number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.date()
  declare delaiSouhaite: DateTime | null
  @column()
  declare description: string
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare localisationAdresse: string
  @column()
  declare localisationLat: string | null
  @column()
  declare localisationLng: string | null
  @column()
  declare profondeurEstimee: string | null
  @column()
  declare statut: string
  @column()
  declare typeForage: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column.dateTime()
  declare validatedAt: DateTime | null
  @column()
  declare validatedBy: number | null
}

export class DocumentSchema extends BaseModel {
  static $columns = ['chemin', 'createdAt', 'entityId', 'entityType', 'id', 'mimeType', 'nomFichier', 'updatedAt', 'uploadedBy'] as const
  $columns = DocumentSchema.$columns
  @column()
  declare chemin: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare entityId: number
  @column()
  declare entityType: string
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare mimeType: string | null
  @column()
  declare nomFichier: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare uploadedBy: number
}

export class EntrepriseProfileSchema extends BaseModel {
  static $columns = ['createdAt', 'domaines', 'id', 'raisonSociale', 'rccm', 'updatedAt', 'userId', 'validatedAt', 'validatedBy', 'zonesGeographiques'] as const
  $columns = EntrepriseProfileSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare domaines: any | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare raisonSociale: string
  @column()
  declare rccm: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: number
  @column.dateTime()
  declare validatedAt: DateTime | null
  @column()
  declare validatedBy: number | null
  @column()
  declare zonesGeographiques: any | null
}

export class MessageSchema extends BaseModel {
  static $columns = ['contenu', 'createdAt', 'demandeId', 'id', 'lu', 'receiverId', 'senderId', 'updatedAt'] as const
  $columns = MessageSchema.$columns
  @column()
  declare contenu: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare demandeId: number
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare lu: boolean
  @column()
  declare receiverId: number
  @column()
  declare senderId: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class NotificationSettingSchema extends BaseModel {
  static $columns = ['actif', 'createdAt', 'id', 'type', 'updatedAt'] as const
  $columns = NotificationSettingSchema.$columns
  @column()
  declare actif: boolean
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare type: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class NotificationSchema extends BaseModel {
  static $columns = ['canal', 'contenu', 'createdAt', 'envoyeAt', 'id', 'lu', 'type', 'updatedAt', 'userId'] as const
  $columns = NotificationSchema.$columns
  @column()
  declare canal: string
  @column()
  declare contenu: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime()
  declare envoyeAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare lu: boolean
  @column()
  declare type: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: number
}

export class OffreSchema extends BaseModel {
  static $columns = ['appelOffreId', 'createdAt', 'delaiExecution', 'descriptionTechnique', 'entrepriseId', 'id', 'prixHt', 'prixTtc', 'statut', 'updatedAt'] as const
  $columns = OffreSchema.$columns
  @column()
  declare appelOffreId: number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare delaiExecution: number
  @column()
  declare descriptionTechnique: string | null
  @column()
  declare entrepriseId: number
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare prixHt: string
  @column()
  declare prixTtc: string
  @column()
  declare statut: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class OffresFinaleSchema extends BaseModel {
  static $columns = ['createdAt', 'delaiExecution', 'demandeId', 'envoyePar', 'id', 'margeAdmin', 'offreId', 'prixFinalClient', 'resumePrestation', 'statut', 'updatedAt'] as const
  $columns = OffresFinaleSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare delaiExecution: number
  @column()
  declare demandeId: number
  @column()
  declare envoyePar: number
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare margeAdmin: string
  @column()
  declare offreId: number
  @column()
  declare prixFinalClient: string
  @column()
  declare resumePrestation: string | null
  @column()
  declare statut: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class UserSchema extends BaseModel {
  static $columns = ['createdAt', 'email', 'fullName', 'id', 'isActive', 'password', 'role', 'telephone', 'updatedAt', 'userType'] as const
  $columns = UserSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare email: string
  @column()
  declare fullName: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare isActive: boolean
  @column({ serializeAs: null })
  declare password: string
  @column()
  declare role: string
  @column()
  declare telephone: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userType: string | null
}
